services:
  spendreportaiapi:
    image: spendreportaiapi
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 indexer\new_indexer.py "]
    ports:
      - 5678:5678
